config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :posts
    resources :follows, only: [:create]
  end

  resources :follows, only: [:destroy]

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_up: 'register',
    sign_out: 'logout'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#index'
  resources :pages, only: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord
  #belongs_to :user
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :liked_on, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, as: :liked_on

  def change_color(post, user)
    like = post.likes.where(user_id: user).count
    if like == 1
      "red-500"
    else
      ""
    end
  end

  def change_class(post, user)
    like = post.likes.where(user_id: user).count
    if like == 0
      "regular"
    else
      "solid"
    end
  end

  def name_users(post)

    if post.likes.count > 0

      like = post.likes.first
      user = User.find(like.user_id)
      user.user_name

      if post.likes.count > 2
        "A #{user.user_name} y otras #{post.likes.count - 1} les gusta esto"
      elsif post.likes.count == 2
        "A #{user.user_name} y a otra persona les gusta esto"
      elsif post.likes.count == 1
        "A #{user.user_name} le gusta esto"
      else
        ""
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :followers, class_name: "Follow", foreign_key: "followed_id"
  has_many :following, class_name: "Follow", foreign_key: "follower_id"
  has_many :posts
  has_many :likes
  validates :name, presence: true, length: {maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :user_name])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    other_user = User.find(params[:user_id])
    @fol = Follow.new(follower_id: current_user.id,
                      followed_id: other_user.id)
    @fol.save
    redirect_to user_posts_path(other_user)
  end

  def destroy
    @fol = Follow.find_by(followed_id: params[:id])
    @fol.destroy
    redirect_to user_posts_path(@fol.followed.id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET users/1/posts
  def index
    @posts = @user.posts.order(created_at: :desc)
    @fol = @user.followers.where(follower: current_user)
  end

  # GET users/1/posts/1
  def show

  end

  # GET users/1/posts/new
  def new
    @post = @user.posts.build
  end

  # GET users/1/posts/1/edit
  def edit
  end

  # POST users/1/posts
  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to(root_path, notice: 'Post was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT users/1/posts/1
  def update
    if @post.update_attributes(post_params)
      redirect_to([@post.user, @post], notice: 'Post was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE users/1/posts/1
  def destroy
    @post.destroy

    redirect_to user_posts_url(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_post
      @post = @user.posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:description, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_post.html.slim
= link_to post.user.user_name, user_posts_path(post.user.id), class: 'font-bold'
br
= image_tag post.image if post.image.attached?
p
  strong class="mr-2" #{post.user.user_name}
  span #{post.description}
span #{post.created_at}
br

i [data-reflex="click->post#like"
  data-post_id="#{post.id}"
  data-user_id="#{current_user.id}"
  class="fa-#{post.change_class(post, current_user.id)} \
  fa-heart cursor-pointer text-2xl text-#{post.change_color(post, current_user.id)}"  ]

p
  strong #{post.name_users(post)}

p
  strong #{post.likes.count} Me gusta
br
br

app/views/pages/index.html.slim
= link_to 'logout', destroy_user_session_path, data: {turbo_method: :delete}

= link_to ' Profile', user_posts_path(current_user.id)
br
br

== render partial: 'post', collection: @posts

app/views/posts/_form.html.slim
div class="w-4/5 m-auto p-10 shadow-md rounded"
  = form_for( [@post.user, @post] ) do |f|
    - if @post.errors.any?
      div id="error_explanation"
        h2 "#{pluralize(@post.errors.count, "error")} prohibited this task from being save:"
        ul
          - @post.errors.full_messages.each do |message|
            li = message

    .field
      = f.label :description
      = f.text_field :description, class: "w-full mb-5 rounded-md border-gray-300"

    .field
      = f.label :user_id
      = f.text_field :user_id, class: "w-full mb-5 rounded-md border-gray-300"
    .field
      = f.file_field :image

    .action
      = f.submit

app/views/posts/_post.html.slim
= image_tag post.image if post.image.attached?
p
  strong class="mr-2" #{post.user.user_name}
  span #{post.description}
span #{post.created_at}
br

i [data-reflex="click->post#like" data-post_id="#{post.id}" data-user_id="#{current_user.id}"
  class="fa-#{post.change_class(post, current_user.id)} fa-heart cursor-pointer text-2xl text-#{post.change_color(post, current_user.id)}"]

p
  strong #{post.likes.count} Me gusta
br
br

app/views/posts/index.html.slim
= link_to 'Home', root_path
'|
- if @user == current_user
  = link_to 'edit profile', edit_user_registration_path
'|
= @user.user_name
'|
span Followers(#{@user.followers.count})
'|
span Followed(#{@user.following.count})
br
br
- if @user != current_user
  = link_to 'Follow', user_follows_path(@user), data: {turbo_method: :post}, class: 'bg-blue-200 p-4' unless @fol.present?
  = link_to 'Unfollow', follow_path(@user), data: {turbo_method: :delete}, class: 'bg-blue-200 p-4' if @fol.present?
br
br
== render partial: 'post', collection: @posts
br
hr
- if @user == current_user
  = link_to 'new Post', new_user_post_path

app/views/posts/new.html.slim
h1 New Task

== render 'form'